### PR TITLE
fix missing _basic_globals / _basic_globals_id

### PR DESCRIPTION
**Pull request by Jan-E**
This one makes it compile. I tried including "ext/standard/basic_functions.h", but that caused other errors, so I copied only the essential part. Including basic_functions.h however is preferable if you or me can make that to work.

### CODE REVIEW

**Comment by edtechd** [comment]
It looks like a workaround and I am not sure that it is correct. I will do some tests a bit later.

**Comment by Jan-E** [comment]
Maybe this gives a clue. If I add #include "ext/standard/basic_functions.h" at the very beginning of library.c I am getting these errors:

```
c:\php-sdk\php70dev\ext\standard\php_filestat.h(87): error C2054: expected '(' to follow 'PHPAPI' (compiling source file ext\redis\library.c)
c:\php-sdk\php70dev\ext\standard\php_filestat.h(87): error C2146: syntax error: missing ')' before identifier 'clear_realpath_cache' (compiling source file ext\redis\library.c)
c:\php-sdk\php70dev\ext\standard\php_filestat.h(87): error C2085: 'php_clear_stat_cache': not in formal parameter list (compiling source file ext\redis\library.c)
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe.  You will be prompted to send an error report to Microsoft later.
```

php_filestat.h is included in basic_functions.h at line 31.

**Comment by Jan-E** [comment]
See https://github.com/edtechd/phpredis/pull/3

**Comment by Jan-E** [comment]
I set up a redis server on a Centos6 machine and connected to that server from my laptop. No problems:

```
D:\phpdev\php70.x64>php-cgi redis.php
X-Powered-By: PHP/7.0.0alpha2
Content-type: text/html; charset=UTF-8

Redis has 0 keys
array(43) {
  ["redis_version"]=>
  string(6) "2.4.10"
  ["redis_git_sha1"]=>
  int(0)
  ["redis_git_dirty"]=>
  int(0)
  ["arch_bits"]=>
  int(64)
  ["multiplexing_api"]=>
  string(5) "epoll"
  ["gcc_version"]=>
  string(5) "4.4.6"
  ["process_id"]=>
  int(5599)
  ["uptime_in_seconds"]=>
  int(387)
  ["uptime_in_days"]=>
  int(0)
  ["lru_clock"]=>
  int(1004043)
  ["used_cpu_sys"]=>
  string(4) "0.00"
  ["used_cpu_user"]=>
  string(4) "0.17"
  ["used_cpu_sys_children"]=>
  string(4) "0.00"
  ["used_cpu_user_children"]=>
  string(4) "0.00"
  ["connected_clients"]=>
  int(1)
  ["connected_slaves"]=>
  int(0)
  ["client_longest_output_list"]=>
  int(0)
  ["client_biggest_input_buf"]=>
  int(0)
  ["blocked_clients"]=>
  int(0)
  ["used_memory"]=>
  int(726112)
  ["used_memory_human"]=>
  string(7) "709.09K"
  ["used_memory_rss"]=>
  int(1613824)
  ["used_memory_peak"]=>
  int(726080)
  ["used_memory_peak_human"]=>
  string(7) "709.06K"
  ["mem_fragmentation_ratio"]=>
  string(4) "2.22"
  ["mem_allocator"]=>
  string(14) "jemalloc-2.2.5"
  ["loading"]=>
  int(0)
  ["aof_enabled"]=>
  int(0)
  ["changes_since_last_save"]=>
  int(0)
  ["bgsave_in_progress"]=>
  int(0)
  ["last_save_time"]=>
  int(1436103406)
  ["bgrewriteaof_in_progress"]=>
  int(0)
  ["total_connections_received"]=>
  int(6)
  ["total_commands_processed"]=>
  int(8)
  ["expired_keys"]=>
  int(0)
  ["evicted_keys"]=>
  int(0)
  ["keyspace_hits"]=>
  int(0)
  ["keyspace_misses"]=>
  int(0)
  ["pubsub_channels"]=>
  int(0)
  ["pubsub_patterns"]=>
  int(0)
  ["latest_fork_usec"]=>
  int(0)
  ["vm_enabled"]=>
  int(0)
  ["role"]=>
  string(6) "master"
}
```

**Pull request merged**
